In [1]:
import pandas as pd
import os
import sys
import numpy as np
import time
import warnings 
warnings.filterwarnings("ignore")

In [102]:
file_01 = r'C:\Users\JC366UJ\OneDrive - EY CHINA\Documents\工作\港中旅\01 年审\港中旅年审9家帐表\4045城市发展\4045序时账202301-202312.XLSX'
file_02 = r'C:\Users\JC366UJ\OneDrive - EY CHINA\Documents\工作\港中旅\01 年审\港中旅年审9家帐表\4045城市发展\4045科目余额表202301-202312.XLSX'
# jet_01 = pd.read_excel(file_01,sheet_name=0,dtype = {'凭证编号' : str})
tb_01 = pd.read_excel(file_02,sheet_name=1,dtype = {'总账科目编码' : str})

In [103]:
tb_01

,会计年度,期间从,期间,公司代码,公司名称,功能范围,功能范围文本,一级科目,二级科目(科目前六位),总账科目编码,...,客户,客户名称,供应商,供应商名称,公司代码货币,期初余额(本位币),本期借方(本位币),本期贷方(本位币),本期余额(本位币),累计余额(本位币)
0,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1001.0,100101.0,1001010000,...,NaN,NaN,NaN,NaN,CNY,573.57,4.286000e+01,3.455000e+01,8.31,581.88
1,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,1441321.06,1.587947e+07,1.527794e+07,601528.19,2042849.25
2,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,20550.41,7.562977e+06,7.570975e+06,-7998.21,12552.20
3,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,49.15,1.011587e+08,1.011569e+08,1790.53,1839.68
4,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,28138.90,6.020000e+01,3.371330e+03,-3311.13,24827.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660014.0,6600140100,...,NaN,NaN,NaN,NaN,CNY,0.00,1.600000e+02,0.000000e+00,160.00,160.00
382,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660033.0,6600330000,...,NaN,NaN,NaN,NaN,CNY,0.00,9.249800e+02,0.000000e+00,924.98,924.98
383,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660098.0,6600980000,...,NaN,NaN,NaN,NaN,CNY,0.00,1.782070e+03,0.000000e+00,1782.07,1782.07
384,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660099.0,6600990000,...,NaN,NaN,NaN,NaN,CNY,0.00,0.000000e+00,5.309795e+06,-5309794.60,-5309794.60
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,CNY,0.00,5.507970e+08,5.507970e+08,0.00,0.00

In [43]:
jet_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8480 entries, 0 to 8479
Data columns (total 87 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   公司代码        8479 non-null   float64
 1   会计年度        8479 non-null   float64
 2   输入日期        8479 non-null   datetime64[ns]
 3   凭证编号        8479 non-null   object
 4   凭证日期        8479 non-null   datetime64[ns]
 5   文本          8479 non-null   object
 6   凭证抬头文本      7117 non-null   object
 7   总帐科目        8479 non-null   float64
 8   总账科目：长文本    8479 non-null   object
 9   凭证货币价值      8479 non-null   float64
 10  凭证货币代码      8479 non-null   object
 11  功能范围        2087 non-null   float64
 12  功能范围：文本     2087 non-null   object
 13  公司代码货币价值    8480 non-null   float64
 14  公司代码货币代码    8480 non-null   object
 15  借/贷标识       8479 non-null   object
 16  凭证类型        8479 non-null   object
 17  分类账         8479 non-null   object
 18  过账日期        8479 non-null   datetime64[ns]
 19  输入时间        8479 non-null   object
 20  行项目         8479 non-null   float64
 21  开户行         879 non-null    float64
 22  帐户标识        879 non-null    object
 23  原因代码        5942 non-null   float64
 24  成本中心        2109 non-null   float64
 25  成本中心：长文本    2109 non-null   object
 26  贸易伙伴编号      516 non-null    float64
 27  反记帐         903 non-null    object
 28  参考码 (标题) 1  4137 non-null   object
 29  备选参考编号      4493 non-null   object
 30  订单          0 non-null      float64
 31  订单：短文本      0 non-null      float64
 32  资产          901 non-null    float64
 33  子编号         901 non-null    float64
 34  资产交易类型      452 non-null    float64
 35  资产价值日       452 non-null    datetime64[ns]
 36  税码          351 non-null    object
 37  项目定义        6770 non-null   object
 38  工作分解结构要素    6770 non-null   object
 39  WBS 元素      6770 non-null   object
 40  存放场所        0 non-null      float64
 41  物料分类        0 non-null      float64
 42  航号航次        0 non-null      float64
 43  金融产品        0 non-null      float64
 44  维修项目        0 non-null      float64
 45  业务子项        123 non-null    float64
 46  收入计量类型      0 non-null      float64
 47  综合项目        0 non-null      float64
 48  变动原因        0 non-null      float64
 49  合同编号        182 non-null    object
 50  车牌号         40 non-null     object
 51  房号          0 non-null      float64
 52  业务小类        4746 non-null   object
 53  预留字段6       0 non-null      float64
 54  预留字段7       0 non-null      float64
 55  付款起算日期      4715 non-null   datetime64[ns]
 56  付款条件        94 non-null     object
 57  天数 1        8479 non-null   float64
 58  净收付到期日      4715 non-null   datetime64[ns]
 59  已清项         8479 non-null   object
 60  清帐凭证        1397 non-null   float64
 61  清算分录日期      1397 non-null   datetime64[ns]
 62  清帐日期        1397 non-null   datetime64[ns]
 63  发票参考号       8479 non-null   float64
 64  参考凭证行项目     8479 non-null   float64
 65  对象键值        8479 non-null   object
 66  参考过程        8479 non-null   object
 67  业务交易类型      8479 non-null   object
 68  事务代码        4524 non-null   object
 69  过账码         8479 non-null   float64
 70  分配          7569 non-null   float64
 71  汇率          1443 non-null   float64
 72  换算日期        8479 non-null   datetime64[ns]
 73  用户名         8479 non-null   object
 74  帐户类型        8479 non-null   object
 75  冲销原因        14 non-null     float64
 76  冲销关于        14 non-null     float64
 77  冲销记帐日期      0 non-null      float64
 78  冲销标识        14 non-null     float64
 79  冲销凭证        8 non-null      object
 80  总帐会计年度      8479 non-null   float64
 81  客户          22 non-null     float64
 82  客户科目：姓名 1   47 non-null     object
 83  客户科目：姓名 2   0 non-null      float64
 84  供应商         1494 non-null   float64
 85  供应商科目：名称 1  2736 non-null   object
 86  供应商科目：名称 2  0 non-null      float64
dtypes: datetime64[ns](9), float64(44), object(34)
memory usage: 5.6+ MB

In [45]:
columns_to_convert = ['凭证编号', '文本', '总帐科目'] 
jet_01[columns_to_convert] = jet_01[columns_to_convert].astype(str)

In [40]:
jet_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8480 entries, 0 to 8479
Data columns (total 87 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   公司代码        8479 non-null   float64
 1   会计年度        8479 non-null   float64
 2   输入日期        8479 non-null   datetime64[ns]
 3   凭证编号        8480 non-null   object
 4   凭证日期        8479 non-null   datetime64[ns]
 5   文本          8480 non-null   object
 6   凭证抬头文本      7117 non-null   object
 7   总帐科目        8480 non-null   object
 8   总账科目：长文本    8479 non-null   object
 9   凭证货币价值      8479 non-null   float64
 10  凭证货币代码      8479 non-null   object
 11  功能范围        2087 non-null   float64
 12  功能范围：文本     2087 non-null   object
 13  公司代码货币价值    8480 non-null   float64
 14  公司代码货币代码    8480 non-null   object
 15  借/贷标识       8479 non-null   object
 16  凭证类型        8479 non-null   object
 17  分类账         8479 non-null   object
 18  过账日期        8479 non-null   datetime64[ns]
 19  输入时间        8479 non-null   object
 20  行项目         8479 non-null   float64
 21  开户行         879 non-null    float64
 22  帐户标识        879 non-null    object
 23  原因代码        5942 non-null   float64
 24  成本中心        2109 non-null   float64
 25  成本中心：长文本    2109 non-null   object
 26  贸易伙伴编号      516 non-null    float64
 27  反记帐         903 non-null    object
 28  参考码 (标题) 1  4137 non-null   object
 29  备选参考编号      4493 non-null   object
 30  订单          0 non-null      float64
 31  订单：短文本      0 non-null      float64
 32  资产          901 non-null    float64
 33  子编号         901 non-null    float64
 34  资产交易类型      452 non-null    float64
 35  资产价值日       452 non-null    datetime64[ns]
 36  税码          351 non-null    object
 37  项目定义        6770 non-null   object
 38  工作分解结构要素    6770 non-null   object
 39  WBS 元素      6770 non-null   object
 40  存放场所        0 non-null      float64
 41  物料分类        0 non-null      float64
 42  航号航次        0 non-null      float64
 43  金融产品        0 non-null      float64
 44  维修项目        0 non-null      float64
 45  业务子项        123 non-null    float64
 46  收入计量类型      0 non-null      float64
 47  综合项目        0 non-null      float64
 48  变动原因        0 non-null      float64
 49  合同编号        182 non-null    object
 50  车牌号         40 non-null     object
 51  房号          0 non-null      float64
 52  业务小类        4746 non-null   object
 53  预留字段6       0 non-null      float64
 54  预留字段7       0 non-null      float64
 55  付款起算日期      4715 non-null   datetime64[ns]
 56  付款条件        94 non-null     object
 57  天数 1        8479 non-null   float64
 58  净收付到期日      4715 non-null   datetime64[ns]
 59  已清项         8479 non-null   object
 60  清帐凭证        1397 non-null   float64
 61  清算分录日期      1397 non-null   datetime64[ns]
 62  清帐日期        1397 non-null   datetime64[ns]
 63  发票参考号       8479 non-null   float64
 64  参考凭证行项目     8479 non-null   float64
 65  对象键值        8479 non-null   object
 66  参考过程        8479 non-null   object
 67  业务交易类型      8479 non-null   object
 68  事务代码        4524 non-null   object
 69  过账码         8479 non-null   float64
 70  分配          7569 non-null   float64
 71  汇率          1443 non-null   float64
 72  换算日期        8479 non-null   datetime64[ns]
 73  用户名         8479 non-null   object
 74  帐户类型        8479 non-null   object
 75  冲销原因        14 non-null     float64
 76  冲销关于        14 non-null     float64
 77  冲销记帐日期      0 non-null      float64
 78  冲销标识        14 non-null     float64
 79  冲销凭证        8 non-null      object
 80  总帐会计年度      8479 non-null   float64
 81  客户          22 non-null     float64
 82  客户科目：姓名 1   47 non-null     object
 83  客户科目：姓名 2   0 non-null      float64
 84  供应商         1494 non-null   float64
 85  供应商科目：名称 1  2736 non-null   object
 86  供应商科目：名称 2  0 non-null      float64
dtypes: datetime64[ns](9), float64(43), object(35)
memory usage: 5.6+ MB

In [46]:
selected_columns = ['公司代码', '会计年度', '输入日期', '凭证编号', '凭证日期', '文本', '凭证抬头文本', '总帐科目',
       '总账科目：长文本', '凭证货币价值', '凭证货币代码', '功能范围', '功能范围：文本']
jet_01[selected_columns]

,公司代码,会计年度,输入日期,凭证编号,凭证日期,文本,凭证抬头文本,总帐科目,总账科目：长文本,凭证货币价值,凭证货币代码,功能范围,功能范围：文本
0,NaN,NaN,NaT,nan,NaT,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN
1,4045.0,2023.0,2023-12-30,8200000529,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000.0,营业外收入-应付款回拨,-97339.13,CNY,NaN,NaN
2,4045.0,2023.0,2023-12-30,8200000529,2023-12-28,球会应退会籍费^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2241120000.0,其他应付款-预提费用,9936895.06,CNY,NaN,NaN
3,4045.0,2023.0,2023-12-30,8200000529,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6801020000.0,所得税费用-递延所得税费用,2202329.99,CNY,NaN,NaN
4,4045.0,2023.0,2023-12-30,8200000529,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000.0,营业外收入-应付款回拨,-9936895.06,CNY,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8475,4045.0,2023.0,2022-12-26,6200000015,2023-01-01,* 利息计提回转 0000230001158,NaN,5002080100.0,开发成本-资本化财务费用-资本化利息,-11126.22,CNY,NaN,NaN
8476,4045.0,2023.0,2022-12-26,6200000016,2023-01-01,* 利息计提回转 0000230001206,NaN,5002080100.0,开发成本-资本化财务费用-资本化利息,-24691.81,CNY,NaN,NaN
8477,4045.0,2023.0,2022-12-26,6200000016,2023-01-01,* 利息计提回转 0000230001206,NaN,2501010200.0,长期借款-应计利息,24691.81,CNY,NaN,NaN
8478,4045.0,2023.0,2022-12-26,6200000017,2023-01-01,* 利息计提回转 0000230001209,NaN,5002080100.0,开发成本-资本化财务费用-资本化利息,-13450.28,CNY,NaN,NaN
8479,4045.0,2023.0,2022-12-26,6200000017,2023-01-01,* 利息计提回转 0000230001209,NaN,2501010200.0,长期借款-应计利息,13450.28,CNY,NaN,NaN

In [19]:
jet_001=jet_01.dropna(subset=['公司代码'])
jet_001.head()

,公司代码,会计年度,输入日期,凭证编号,凭证日期,文本,凭证抬头文本,总帐科目,总账科目：长文本,凭证货币价值,...,冲销记帐日期,冲销标识,冲销凭证,总帐会计年度,客户,客户科目：姓名 1,客户科目：姓名 2,供应商,供应商科目：名称 1,供应商科目：名称 2
1,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6.301030e+09,营业外收入-应付款回拨,-97339.13,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
2,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,球会应退会籍费^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2.241120e+09,其他应付款-预提费用,9936895.06,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,100121373.0,原聚豪球会会籍清退虚拟客商,NaN
3,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6.801020e+09,所得税费用-递延所得税费用,2202329.99,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6.301030e+09,营业外收入-应付款回拨,-9936895.06,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
5,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,调整预提球会会籍清退法院诉讼费的业务小类^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2.241120e+09,其他应付款-预提费用,97339.13,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,100000964.0,深圳市财政局,NaN

In [48]:
start_strings = [str(i) for i in range(6001, 6302)]
jet_01['总帐科目'] = jet_01['总帐科目'].astype(str)
jet_unique = jet_01[(jet_01['借/贷标识']=='H') & (jet_01['总帐科目'].str.startswith(tuple(start_strings)))]['凭证编号'].unique()

In [60]:
drop_values = ('1122', '2203', '2204', '1001')

jet_01[jet_01['凭证编号'].isin(jet_unique) & (jet_01['借/贷标识'] == 'S') & 
       (~jet_01['总帐科目'].astype(str).str.startswith(drop_values))]['总帐科目'].unique()

array(['2241120000.0', '6801020000.0', '2202030000.0', '1002010000.0'],
      dtype=object)

In [66]:
jet_001['总帐科目'].info()

<class 'pandas.core.series.Series'>
Index: 8479 entries, 1 to 8479
Series name: 总帐科目
Non-Null Count  Dtype
--------------  -----
8479 non-null   object
dtypes: object(1)
memory usage: 132.5+ KB

In [115]:
jet_001['总帐科目'] = jet_001['总帐科目'].astype(float).astype('int64').astype(str)
# jet_001['总帐科目']

In [80]:
jet_001[~jet_001['业务交易类型'].isnull()]

,公司代码,会计年度,输入日期,凭证编号,凭证日期,文本,凭证抬头文本,总帐科目,总账科目：长文本,凭证货币价值,...,冲销记帐日期,冲销标识,冲销凭证,总帐会计年度,客户,客户科目：姓名 1,客户科目：姓名 2,供应商,供应商科目：名称 1,供应商科目：名称 2
1,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000.0,营业外收入-应付款回拨,-97339.13,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
2,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,球会应退会籍费^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2241120000.0,其他应付款-预提费用,9936895.06,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,100121373.0,原聚豪球会会籍清退虚拟客商,NaN
3,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6801020000.0,所得税费用-递延所得税费用,2202329.99,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000.0,营业外收入-应付款回拨,-9936895.06,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
5,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,调整预提球会会籍清退法院诉讼费的业务小类^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2241120000.0,其他应付款-预提费用,97339.13,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,100000964.0,深圳市财政局,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8475,4045.0,2023.0,2022-12-26,6.200000e+09,2023-01-01,* 利息计提回转 0000230001158,NaN,5002080100.0,开发成本-资本化财务费用-资本化利息,-11126.22,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
8476,4045.0,2023.0,2022-12-26,6.200000e+09,2023-01-01,* 利息计提回转 0000230001206,NaN,5002080100.0,开发成本-资本化财务费用-资本化利息,-24691.81,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
8477,4045.0,2023.0,2022-12-26,6.200000e+09,2023-01-01,* 利息计提回转 0000230001206,NaN,2501010200.0,长期借款-应计利息,24691.81,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
8478,4045.0,2023.0,2022-12-26,6.200000e+09,2023-01-01,* 利息计提回转 0000230001209,NaN,5002080100.0,开发成本-资本化财务费用-资本化利息,-13450.28,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
8479,4045.0,2023.0,2022-12-26,6.200000e+09,2023-01-01,* 利息计提回转 0000230001209,NaN,2501010200.0,长期借款-应计利息,13450.28,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
jet_001[jet_001['文本'].str.contains('利息', na=False)].shape
# [['文本']]

(1646, 87)

In [134]:
tb_01.rename(columns={'总账科目编码': '总帐科目'})
tb_01

,会计年度,期间从,期间,公司代码,公司名称,功能范围,功能范围文本,一级科目,二级科目(科目前六位),总帐科目,...,客户,客户名称,供应商,供应商名称,公司代码货币,期初余额(本位币),本期借方(本位币),本期贷方(本位币),本期余额(本位币),累计余额(本位币)
0,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1001.0,100101.0,1001010000,...,NaN,NaN,NaN,NaN,CNY,573.57,4.286000e+01,3.455000e+01,8.31,581.88
1,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,1441321.06,1.587947e+07,1.527794e+07,601528.19,2042849.25
2,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,20550.41,7.562977e+06,7.570975e+06,-7998.21,12552.20
3,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,49.15,1.011587e+08,1.011569e+08,1790.53,1839.68
4,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,NaN,NaN,1002.0,100201.0,1002010000,...,NaN,NaN,NaN,NaN,CNY,28138.90,6.020000e+01,3.371330e+03,-3311.13,24827.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660014.0,6600140100,...,NaN,NaN,NaN,NaN,CNY,0.00,1.600000e+02,0.000000e+00,160.00,160.00
382,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660033.0,6600330000,...,NaN,NaN,NaN,NaN,CNY,0.00,9.249800e+02,0.000000e+00,924.98,924.98
383,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660098.0,6600980000,...,NaN,NaN,NaN,NaN,CNY,0.00,1.782070e+03,0.000000e+00,1782.07,1782.07
384,2023.0,1.0,12.0,4045.0,中旅（深圳）城市发展有限公司,6000.0,开发间接费,6600.0,660099.0,6600990000,...,NaN,NaN,NaN,NaN,CNY,0.00,0.000000e+00,5.309795e+06,-5309794.60,-5309794.60
385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,CNY,0.00,5.507970e+08,5.507970e+08,0.00,0.00

In [117]:
merged_df = jet_001.merge(tb_01, on=['总帐科目', '公司代码'], how='inner')
merged_df

,公司代码,会计年度_x,输入日期,凭证编号,凭证日期,文本,凭证抬头文本,总帐科目,总账科目：长文本,凭证货币价值,...,客户_y,客户名称,供应商_y,供应商名称,公司代码货币,期初余额(本位币),本期借方(本位币),本期贷方(本位币),本期余额(本位币),累计余额(本位币)
0,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000,营业外收入-应付款回拨,-97339.13,...,NaN,NaN,NaN,NaN,CNY,0.00,0.00,13356558.92,-13356558.92,-13356558.92
1,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000,营业外收入-应付款回拨,-9936895.06,...,NaN,NaN,NaN,NaN,CNY,0.00,0.00,13356558.92,-13356558.92,-13356558.92
2,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,6301030000,营业外收入-应付款回拨,-3322324.73,...,NaN,NaN,NaN,NaN,CNY,0.00,0.00,13356558.92,-13356558.92,-13356558.92
3,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,球会应退会籍费^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2241120000,其他应付款-预提费用,9936895.06,...,NaN,NaN,100000964.0,深圳市财政局,CNY,-1065122.54,109051.96,50.00,109001.96,-956120.58
4,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,球会应退会籍费^30004671^30026322,冲销多预提球会会籍清退补偿款及诉讼费,2241120000,其他应付款-预提费用,9936895.06,...,NaN,NaN,100073021.0,毕马威华振会计师事务所（特殊普通合伙）深圳分所,CNY,-27405.66,27405.66,0.00,27405.66,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49275,4045.0,2023.0,2023-02-06,8.200000e+09,2023-02-06,收到深圳市捷士达实业有限公司投标保证金^30004671^30004671,调整投标保证金挂账客商,2241050000,其他应付款-保证金,20000.00,...,NaN,NaN,100137793.0,深圳市捷士达实业有限公司,CNY,0.00,20000.00,20000.00,0.00,0.00
49276,4045.0,2023.0,2023-02-06,8.200000e+09,2023-02-06,^30004671,调整投标保证金挂账客商,2241050000,其他应付款-保证金,-20000.00,...,NaN,NaN,100052966.0,零星虚拟客商,CNY,-40000.00,40000.00,0.00,40000.00,0.00
49277,4045.0,2023.0,2023-02-06,8.200000e+09,2023-02-06,^30004671,调整投标保证金挂账客商,2241050000,其他应付款-保证金,-20000.00,...,NaN,NaN,100099428.0,中建新疆建工（集团）有限公司,CNY,-1311697.08,0.00,0.00,0.00,-1311697.08
49278,4045.0,2023.0,2023-02-06,8.200000e+09,2023-02-06,^30004671,调整投标保证金挂账客商,2241050000,其他应付款-保证金,-20000.00,...,NaN,NaN,100137792.0,深圳市天地照明集团有限公司,CNY,0.00,20000.00,20000.00,0.00,0.00
49279,4045.0,2023.0,2023-02-06,8.200000e+09,2023-02-06,^30004671,调整投标保证金挂账客商,2241050000,其他应付款-保证金,-20000.00,...,NaN,NaN,100137793.0,深圳市捷士达实业有限公司,CNY,0.00,20000.00,20000.00,0.00,0.00

In [122]:
jet_001.groupby('总帐科目')['凭证货币价值', ''].sum()

总帐科目
1001010000           0.00
1002010000    -5962536.17
1122010000       -8000.00
1123010100           0.00
1123020000           0.00
                 ...
6603030100        2947.73
6603040102           0.00
6603040202           0.00
6711020100    15950000.00
6801020000     2474604.10
Name: 凭证货币价值, Length: 145, dtype: float64

In [128]:
jet_001.groupby('总帐科目')['凭证货币价值'].sum().reset_index()

           总帐科目       凭证货币价值
0    1001010000         0.00
1    1002010000  -5962536.17
2    1122010000     -8000.00
3    1123010100         0.00
4    1123020000         0.00
..          ...          ...
140  6603030100      2947.73
141  6603040102         0.00
142  6603040202         0.00
143  6711020100  15950000.00
144  6801020000   2474604.10

[145 rows x 2 columns]

In [133]:
tb_01.groupby('总帐科目').agg({'本期借方(本位币)': 'sum', '期初余额(本位币)': 'sum'}).reset_index().merge(jet_001, on='总帐科目', how = 'inner')

,总帐科目,本期借方(本位币),期初余额(本位币),公司代码,会计年度,输入日期,凭证编号,凭证日期,文本,凭证抬头文本,...,冲销记帐日期,冲销标识,冲销凭证,总帐会计年度,客户,客户科目：姓名 1,客户科目：姓名 2,供应商,供应商科目：名称 1,供应商科目：名称 2
0,1001010000,42.86,573.57,4045.0,2023.0,2023-12-29,7.100000e+09,2023-12-31,1001010000 - 20231231 上评估,0L20231231011001010000,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1001010000,42.86,573.57,4045.0,2023.0,2023-11-30,7.100000e+09,2023-11-30,1001010000 - 20231130 上评估,0L20231130011001010000,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1001010000,42.86,573.57,4045.0,2023.0,2023-10-31,7.100000e+09,2023-10-31,1001010000 - 20231031 上评估,0L20231031011001010000,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1001010000,42.86,573.57,4045.0,2023.0,2023-09-28,7.100000e+09,2023-09-30,1001010000 - 20230930 上评估,0L20230930011001010000,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1001010000,42.86,573.57,4045.0,2023.0,2023-08-31,7.100000e+09,2023-08-31,1001010000 - 20230831 上评估,0L20230831011001010000,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8453,6711020100,15950000.00,0.00,4045.0,2023.0,2023-09-04,8.200000e+09,2023-09-04,王金福报营业外支出-捐赠支出-定点扶贫地区^30026322,申请拨付香格里拉市定向帮扶资金,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,香格里拉市乡村振兴局,NaN
8454,6711020100,15950000.00,0.00,4045.0,2023.0,2023-06-30,8.200000e+09,2023-06-30,易文涛报营业外支出-捐赠支出-定点扶贫地区^30004671,申请拨付德钦县定向帮扶资金,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,德钦县乡村振兴局,NaN
8455,6711020100,15950000.00,0.00,4045.0,2023.0,2023-06-29,8.200000e+09,2023-06-28,易文涛报营业外支出-捐赠支出-定点扶贫地区^30004671,申请拨付香格里拉市定向帮扶资金,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,香格里拉市乡村振兴局,NaN
8456,6801020000,2474604.10,0.00,4045.0,2023.0,2023-12-30,8.200001e+09,2023-12-28,^30026322,冲销多预提球会会籍清退补偿款及诉讼费,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN
8457,6801020000,2474604.10,0.00,4045.0,2023.0,2023-12-15,8.200000e+09,2023-12-15,^30026322,申请调整递延所得税负债,...,NaN,NaN,NaN,2023.0,NaN,NaN,NaN,NaN,NaN,NaN

测试

In [8]:
import pandas as pd
import glob

# 获取所有需要读取的文件名
file_list = glob.glob("C:/Users/JC366UJ/OneDrive - EY CHINA/Documents/个人/01 code test/data test/测试/*.csv")  # 根据具体情况设定文件路径

# 初始化一个空的 DataFrame 列表
data_frames = []

# 循环读取并合并数据
for file in file_list:
    data = pd.read_csv(file,encoding='GB18030')
    data_frames.append(data)

# 合并所有 DataFrame
combined_data = pd.concat(data_frames, ignore_index=True)

# 打印合并后的数据
print(combined_data)

C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')
C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')
C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')
C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')
C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')
C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')

              输入日期          凭证编号          总帐科目           总账科目：长文本    功能范围  \
0              NaN           NaN           NaN                NaN     NaN
1       2023/12/29  3.010000e+09  6.600130e+09  共性费用-折旧摊销费-固定资产折旧  5000.0
2       2023/12/29  3.010000e+09  6.600130e+09  共性费用-折旧摊销费-固定资产折旧  5000.0
3       2023/12/29  3.010000e+09  6.600130e+09  共性费用-折旧摊销费-固定资产折旧  5000.0
4       2023/12/29  3.010000e+09  6.600130e+09  共性费用-折旧摊销费-固定资产折旧  5000.0
...            ...           ...           ...                ...     ...
128837  2022/12/28  7.200000e+09  1.221999e+09        其他应收款-重分类调整     NaN
128838  2022/12/28  7.200000e+09  1.122999e+09         应收账款-重分类调整     NaN
128839  2022/12/28  7.200000e+09  2.203999e+09         预收账款-重分类调整     NaN
128840  2022/12/28  7.200000e+09  2.203999e+09         预收账款-重分类调整     NaN
128841  2022/12/28  7.200000e+09  1.122999e+09         应收账款-重分类调整     NaN

       功能范围：文本              凭证抬头文本                             文本   公司代码货币价值  \
0          NaN                 NaN                            NaN       0.00
1       主营业务成本  AFB/01/2023/012/01             AFB/01/2023/012/01   1,835.80
2       主营业务成本  AFB/01/2023/012/01             AFB/01/2023/012/01  51,144.79
3       主营业务成本  AFB/01/2023/012/01             AFB/01/2023/012/01   1,705.40
4       主营业务成本  AFB/01/2023/012/01             AFB/01/2023/012/01   1,417.44
...        ...                 ...                            ...        ...
128837     NaN       冲销过帐 FAGLF101  基于贷方余额需要调整转出的科目 科目 1221180000  -5,851.44
128838     NaN       冲销过帐 FAGLF101  基于借方余额需要调整转出的科目 科目 2203000000    -157.00
128839     NaN       冲销过帐 FAGLF101  基于借方余额需要调整转出的科目 科目 2203000000     157.00
128840     NaN       冲销过帐 FAGLF101  基于借方余额需要调整转出的科目 科目 2203000000    -157.00
128841     NaN       冲销过帐 FAGLF101  基于借方余额需要调整转出的科目 科目 2203000000     157.00

       公司代码货币代码  ...    会计年度        凭证日期  总帐会计年度 借/贷标识  客户 客户科目：姓名 1  \
0           CNY  ...     NaN         NaN     NaN   NaN NaN       NaN
1           CNY  ...  2023.0  2023/12/31  2023.0     S NaN       NaN
2           CNY  ...  2023.0  2023/12/31  2023.0     S NaN       NaN
3           CNY  ...  2023.0  2023/12/31  2023.0     S NaN       NaN
4           CNY  ...  2023.0  2023/12/31  2023.0     S NaN       NaN
...         ...  ...     ...         ...     ...   ...  ..       ...
128837      CNY  ...  2023.0  2022/12/31  2023.0     H NaN       NaN
128838      CNY  ...  2023.0  2022/12/31  2023.0     H NaN       NaN
128839      CNY  ...  2023.0  2022/12/31  2023.0     S NaN       NaN
128840      CNY  ...  2023.0  2022/12/31  2023.0     H NaN       NaN
128841      CNY  ...  2023.0  2022/12/31  2023.0     S NaN       NaN

       客户科目：姓名 2  供应商 供应商科目：名称 1  供应商科目：名称 2
0            NaN  NaN        NaN         NaN
1            NaN  NaN        NaN         NaN
2            NaN  NaN        NaN         NaN
3            NaN  NaN        NaN         NaN
4            NaN  NaN        NaN         NaN
...          ...  ...        ...         ...
128837       NaN  NaN        NaN         NaN
128838       NaN  NaN        NaN         NaN
128839       NaN  NaN        NaN         NaN
128840       NaN  NaN        NaN         NaN
128841       NaN  NaN        NaN         NaN

[128842 rows x 87 columns]

C:\Users\JC366UJ\AppData\Local\Temp\ipykernel_11448\4178853405.py:12: DtypeWarning: Columns (52,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file,encoding='GB18030')

In [15]:
combined_data[combined_data['总帐科目'].isnull()]

,输入日期,凭证编号,总帐科目,总账科目：长文本,功能范围,功能范围：文本,凭证抬头文本,文本,公司代码货币价值,公司代码货币代码,...,会计年度,凭证日期,总帐会计年度,借/贷标识,客户,客户科目：姓名 1,客户科目：姓名 2,供应商,供应商科目：名称 1,供应商科目：名称 2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,CNY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
file_ = r'C:\Users\JC366UJ\OneDrive - EY CHINA\Documents\个人\01 code test'
file_

'C:\\Users\\JC366UJ\\OneDrive - EY CHINA\\Documents\\个人\\01 code test'

In [8]:
import pandas as pd

# 创建示例 DataFrame A 和 B
data_A = {'ID': [1, 2, 3, 4, 5],
          'Value_A': ['A1', 'A2', 'A3', 'A4', 'A5']}
data_B = {'ID': [1, 2, 3],
          'Value_B': ['B1', 'B2', 'B3']}
df_A = pd.DataFrame(data_A)
df_B = pd.DataFrame(data_B)

# 使用 merge 合并，并标记记录来源
merged_df = df_A.merge(df_B, on='ID', how='right', indicator=True)

# 筛选出 A 比 B 多的记录
A_more_than_B = merged_df[merged_df['_merge'] == 'left_only']

print(A_more_than_B)

Empty DataFrame
Columns: [ID, Value_A, Value_B, _merge]
Index: []

In [10]:
merged_df

   ID Value_A Value_B _merge
0   1      A1      B1   both
1   2      A2      B2   both
2   3      A3      B3   both

In [3]:
df_B

   ID Value_B
0   1      B1
1   2      B2
2   3      B3